apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy-jaska
  annotations:
    kubernetes.io/change-cause: "Update to version nginx:perl"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-deploy-jaska
  strategy: {}
  template:
    metadata:
      labels:
        app: web-deploy-jaska
    spec:
      containers:
      - image: nginx:perl 
        name: nginx 
        ports:
        - containerPort: 80
        resources: {}

