apiVersion: v1
kind: Service
metadata:
  labels:
    run: mywordpress
  name: mywordpress
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    run: mywordpress
