apiVersion: v1
kind: Service
metadata:
  name: myweb1-service
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30007
  selector:
    appName: myweb1app
    market: kg
