apiVersion: v1
kind: Pod
metadata:
  name: talant
spec:
  containers:
  - name: app
    image: ubuntu
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    args:
      - sleep
      - "3600"
    