apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: web 
spec: 
  containers:
  - name: redis 
    image: redis 
    ports:
      - name: redis 
        containerPort: 9090
        protocol: TCP 